name: "Build and Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ["*"]

jobs:
  #TODO(@Xunzhuo): add lint tools to do static code analyse.
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  coverage-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # test
    - name: Run Coverage Tests
      run: GOPROXY="https://proxy.golang.org,direct" make go.test.coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        verbose: true

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint,coverage-test]
    strategy:
      matrix:
        golang:
          - 1.19
    steps:
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "checkout ${{ github.ref }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "Build Higress Binary"
        run: GOPROXY="https://proxy.golang.org,direct" make build

      - name: Upload Higress Binary
        uses: actions/upload-artifact@v3
        with:
          name: higress
          path: out/

  conformance-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3

  e2e-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3

  publish:
    runs-on: ubuntu-latest
    needs: [conformance-test,e2e-test]
    steps:
    - uses: actions/checkout@v3
